[remote.github]
owner = "RustSync"
repo = "RustSyncCV-Client"

[changelog]
header = """
# æ›´æ–°æ—¥å¿— ğŸš€
"""

body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}]({{ self::remote_url() }}/releases/tag/{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
{% else %}\
    ## æœªå‘å¸ƒ
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}**({{ commit.scope }})** {% endif %}\
          {{ commit.message | split(pat="\n") | first | upper_first }} \
          ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }})) \
          by @{{ commit.author.name }}
    {% endfor %}
{% endfor %}

{%- if github -%}
{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  ## è´¡çŒ®è€…ä»¬ â¤ï¸
{% endif %}\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} æäº¤äº†ä»–ä»¬çš„é¦–ä¸ªè´¡çŒ® \
    {%- if contributor.pr_number %} (PR [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }})) {%- endif %}
{%- endfor -%}
{%- endif %}
"""

footer = """
---
**å®Œæ•´å˜æ›´åˆ—è¡¨**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
"""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
    { message = "^feat", group = "âœ¨ æ–°åŠŸèƒ½" },
    { message = "^fix", group = "ğŸ› Bug ä¿®å¤" },
    { message = "^doc", group = "ğŸ“š æ–‡æ¡£" },
    { message = "^perf", group = "ğŸš€ æ€§èƒ½ä¼˜åŒ–" },
    { message = "^refactor", group = "ğŸšœ ä»£ç é‡æ„" },
    { message = "^style", group = "ğŸ¨ æ ·å¼" },
    { message = "^test", group = "ğŸ§ª æµ‹è¯•" },
    { message = "^chore\\(deps\\)", group = "ğŸ“¦ ä¾èµ–æ›´æ–°" },
    { message = "^chore", group = "ğŸ”§ æ—¥å¸¸ç»´æŠ¤" },
    { message = "^ci", group = "âš™ï¸ æŒç»­é›†æˆ" },
    { body = ".*security", group = "ğŸ”’ å®‰å…¨" },
    { message = "^revert", group = "â—€ï¸ æ’¤é”€" },
    { message = ".*", group = "å…¶ä»–å˜æ›´" },
]
# ä¿æŠ¤æ‰“ç ´å…¼å®¹æ€§çš„æ”¹åŠ¨
protect_breaking_commits = false
# å¿½ç•¥çš„æ ‡ç­¾
ignore_tags = ""
# æ’åº
sort_commits = "oldest"

[git.github]
commits = true
